# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'bid.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_BidBETONA(object):
    def setupUi(self, BidBETONA):
        if not BidBETONA.objectName():
            BidBETONA.setObjectName(u"BidBETONA")
        BidBETONA.resize(1278, 824)
        BidBETONA.setStyleSheet(u"background-color: rgb(255, 255, 255)")
        self.centralwidget = QWidget(BidBETONA)
        self.centralwidget.setObjectName(u"centralwidget")
        self.bidTitle = QLabel(self.centralwidget)
        self.bidTitle.setObjectName(u"bidTitle")
        self.bidTitle.setGeometry(QRect(10, 10, 451, 61))
        self.bidTitle.setPixmap(QPixmap(u"bidtitle.png"))
        self.frame3 = QFrame(self.centralwidget)
        self.frame3.setObjectName(u"frame3")
        self.frame3.setGeometry(QRect(400, 130, 311, 481))
        font = QFont()
        font.setFamily(u"\ub098\ub214\uace0\ub515")
        font.setPointSize(10)
        self.frame3.setFont(font)
        self.frame3.setAutoFillBackground(False)
        self.frame3.setStyleSheet(u"background-color: rgb(255, 255, 255)")
        self.frame3.setFrameShape(QFrame.StyledPanel)
        self.frame3.setFrameShadow(QFrame.Raised)
        self.txtResult5_2 = QLineEdit(self.frame3)
        self.txtResult5_2.setObjectName(u"txtResult5_2")
        self.txtResult5_2.setGeometry(QRect(90, 20, 191, 20))
        self.label_19 = QLabel(self.frame3)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(20, 20, 61, 21))
        self.label_20 = QLabel(self.frame3)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(20, 50, 61, 21))
        self.label_21 = QLabel(self.frame3)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(20, 80, 61, 21))
        self.txtResult7_2 = QLineEdit(self.frame3)
        self.txtResult7_2.setObjectName(u"txtResult7_2")
        self.txtResult7_2.setGeometry(QRect(90, 80, 191, 20))
        self.comboBox_2 = QComboBox(self.frame3)
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(90, 50, 191, 22))
        self.label_10 = QLabel(self.frame3)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(110, 110, 61, 16))
        self.txtResult9_2 = QLineEdit(self.frame3)
        self.txtResult9_2.setObjectName(u"txtResult9_2")
        self.txtResult9_2.setGeometry(QRect(30, 140, 111, 20))
        self.label_15 = QLabel(self.frame3)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 140, 16, 21))
        self.txtResult9_3 = QLineEdit(self.frame3)
        self.txtResult9_3.setObjectName(u"txtResult9_3")
        self.txtResult9_3.setGeometry(QRect(30, 170, 111, 20))
        self.label_16 = QLabel(self.frame3)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 170, 16, 21))
        self.txtResult9_4 = QLineEdit(self.frame3)
        self.txtResult9_4.setObjectName(u"txtResult9_4")
        self.txtResult9_4.setGeometry(QRect(30, 200, 111, 20))
        self.label_17 = QLabel(self.frame3)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 200, 16, 21))
        self.txtResult9_5 = QLineEdit(self.frame3)
        self.txtResult9_5.setObjectName(u"txtResult9_5")
        self.txtResult9_5.setGeometry(QRect(30, 230, 111, 20))
        self.label_18 = QLabel(self.frame3)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 230, 16, 21))
        self.txtResult9_6 = QLineEdit(self.frame3)
        self.txtResult9_6.setObjectName(u"txtResult9_6")
        self.txtResult9_6.setGeometry(QRect(30, 260, 111, 20))
        self.label_22 = QLabel(self.frame3)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(10, 260, 16, 21))
        self.txtResult9_7 = QLineEdit(self.frame3)
        self.txtResult9_7.setObjectName(u"txtResult9_7")
        self.txtResult9_7.setGeometry(QRect(30, 290, 111, 20))
        self.label_23 = QLabel(self.frame3)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(10, 290, 16, 21))
        self.txtResult9_8 = QLineEdit(self.frame3)
        self.txtResult9_8.setObjectName(u"txtResult9_8")
        self.txtResult9_8.setGeometry(QRect(30, 320, 111, 20))
        self.label_24 = QLabel(self.frame3)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(10, 320, 16, 21))
        self.txtResult9_9 = QLineEdit(self.frame3)
        self.txtResult9_9.setObjectName(u"txtResult9_9")
        self.txtResult9_9.setGeometry(QRect(180, 140, 111, 20))
        self.label_25 = QLabel(self.frame3)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(160, 140, 16, 21))
        self.txtResult9_10 = QLineEdit(self.frame3)
        self.txtResult9_10.setObjectName(u"txtResult9_10")
        self.txtResult9_10.setGeometry(QRect(180, 170, 111, 20))
        self.label_26 = QLabel(self.frame3)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(160, 170, 16, 21))
        self.txtResult9_11 = QLineEdit(self.frame3)
        self.txtResult9_11.setObjectName(u"txtResult9_11")
        self.txtResult9_11.setGeometry(QRect(180, 200, 111, 20))
        self.label_27 = QLabel(self.frame3)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(160, 200, 16, 21))
        self.txtResult9_12 = QLineEdit(self.frame3)
        self.txtResult9_12.setObjectName(u"txtResult9_12")
        self.txtResult9_12.setGeometry(QRect(180, 230, 111, 20))
        self.label_28 = QLabel(self.frame3)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(160, 230, 16, 21))
        self.txtResult9_13 = QLineEdit(self.frame3)
        self.txtResult9_13.setObjectName(u"txtResult9_13")
        self.txtResult9_13.setGeometry(QRect(180, 260, 111, 20))
        self.label_29 = QLabel(self.frame3)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(160, 260, 16, 21))
        self.txtResult9_14 = QLineEdit(self.frame3)
        self.txtResult9_14.setObjectName(u"txtResult9_14")
        self.txtResult9_14.setGeometry(QRect(180, 290, 111, 20))
        self.label_30 = QLabel(self.frame3)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(160, 290, 16, 21))
        self.txtResult9_15 = QLineEdit(self.frame3)
        self.txtResult9_15.setObjectName(u"txtResult9_15")
        self.txtResult9_15.setGeometry(QRect(180, 320, 111, 20))
        self.label_31 = QLabel(self.frame3)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(160, 320, 16, 21))
        self.txtResult9_16 = QLineEdit(self.frame3)
        self.txtResult9_16.setObjectName(u"txtResult9_16")
        self.txtResult9_16.setGeometry(QRect(180, 350, 111, 20))
        self.label_32 = QLabel(self.frame3)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(160, 350, 16, 21))
        self.txtDate = QLabel(self.centralwidget)
        self.txtDate.setObjectName(u"txtDate")
        self.txtDate.setGeometry(QRect(230, 90, 131, 16))
        self.txtTime = QLabel(self.centralwidget)
        self.txtTime.setObjectName(u"txtTime")
        self.txtTime.setGeometry(QRect(370, 90, 191, 16))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(1140, 20, 121, 41))
        self.label.setPixmap(QPixmap(u"betonalogo.png"))
        self.label.setScaledContents(True)
        self.btnReset = QPushButton(self.centralwidget)
        self.btnReset.setObjectName(u"btnReset")
        self.btnReset.setGeometry(QRect(1000, 60, 75, 23))
        self.bidNum = QLineEdit(self.centralwidget)
        self.bidNum.setObjectName(u"bidNum")
        self.bidNum.setGeometry(QRect(630, 60, 251, 21))
        self.btnSearch = QPushButton(self.centralwidget)
        self.btnSearch.setObjectName(u"btnSearch")
        self.btnSearch.setGeometry(QRect(900, 60, 75, 23))
        self.label_33 = QLabel(self.centralwidget)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(510, 60, 111, 21))
        self.txtResult1 = QLineEdit(self.centralwidget)
        self.txtResult1.setObjectName(u"txtResult1")
        self.txtResult1.setGeometry(QRect(140, 150, 191, 20))
        self.label_34 = QLabel(self.centralwidget)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(70, 360, 61, 21))
        self.label_35 = QLabel(self.centralwidget)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(70, 450, 61, 21))
        self.comboBox6 = QComboBox(self.centralwidget)
        self.comboBox6.addItem("")
        self.comboBox6.addItem("")
        self.comboBox6.setObjectName(u"comboBox6")
        self.comboBox6.setGeometry(QRect(140, 300, 191, 22))
        self.label_36 = QLabel(self.centralwidget)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(70, 180, 61, 21))
        self.label_37 = QLabel(self.centralwidget)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(70, 210, 61, 21))
        self.label_38 = QLabel(self.centralwidget)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(70, 330, 61, 21))
        self.label_39 = QLabel(self.centralwidget)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(70, 420, 61, 21))
        self.label_40 = QLabel(self.centralwidget)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(70, 240, 61, 21))
        self.label_41 = QLabel(self.centralwidget)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(70, 150, 61, 21))
        self.txtResult4 = QLineEdit(self.centralwidget)
        self.txtResult4.setObjectName(u"txtResult4")
        self.txtResult4.setGeometry(QRect(140, 240, 191, 20))
        self.txtResult2 = QLineEdit(self.centralwidget)
        self.txtResult2.setObjectName(u"txtResult2")
        self.txtResult2.setGeometry(QRect(140, 180, 191, 20))
        self.label_42 = QLabel(self.centralwidget)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(70, 390, 61, 21))
        self.txtResult3 = QLineEdit(self.centralwidget)
        self.txtResult3.setObjectName(u"txtResult3")
        self.txtResult3.setGeometry(QRect(140, 210, 191, 20))
        self.label_43 = QLabel(self.centralwidget)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(70, 300, 61, 21))
        self.txtResult11 = QLineEdit(self.centralwidget)
        self.txtResult11.setObjectName(u"txtResult11")
        self.txtResult11.setGeometry(QRect(140, 450, 191, 20))
        self.txtResult9 = QLineEdit(self.centralwidget)
        self.txtResult9.setObjectName(u"txtResult9")
        self.txtResult9.setGeometry(QRect(140, 390, 191, 20))
        self.txtResult5 = QLineEdit(self.centralwidget)
        self.txtResult5.setObjectName(u"txtResult5")
        self.txtResult5.setGeometry(QRect(140, 270, 191, 20))
        self.txtResult8 = QLineEdit(self.centralwidget)
        self.txtResult8.setObjectName(u"txtResult8")
        self.txtResult8.setGeometry(QRect(140, 360, 191, 20))
        self.txtResult7 = QLineEdit(self.centralwidget)
        self.txtResult7.setObjectName(u"txtResult7")
        self.txtResult7.setGeometry(QRect(140, 330, 191, 20))
        self.label_44 = QLabel(self.centralwidget)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(70, 270, 61, 21))
        self.txtResult10 = QLineEdit(self.centralwidget)
        self.txtResult10.setObjectName(u"txtResult10")
        self.txtResult10.setGeometry(QRect(140, 420, 191, 20))
        BidBETONA.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(BidBETONA)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1278, 21))
        BidBETONA.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(BidBETONA)
        self.statusbar.setObjectName(u"statusbar")
        BidBETONA.setStatusBar(self.statusbar)

        self.retranslateUi(BidBETONA)

        QMetaObject.connectSlotsByName(BidBETONA)
    # setupUi

    def retranslateUi(self, BidBETONA):
        BidBETONA.setWindowTitle(QCoreApplication.translate("BidBETONA", u"Bid BETONA", None))
        self.bidTitle.setText("")
        self.label_19.setText(QCoreApplication.translate("BidBETONA", u"\uae30\ucd08\uae08\uc561", None))
        self.label_20.setText(QCoreApplication.translate("BidBETONA", u"\uc608\uac00\ubc94\uc704", None))
        self.label_21.setText(QCoreApplication.translate("BidBETONA", u"\ub099  \ucc30  \uc728", None))
        self.comboBox_2.setItemText(0, QCoreApplication.translate("BidBETONA", u"-3 ~ +3% (\uc548\uc804\ud589\uc815\ubd80)", None))
        self.comboBox_2.setItemText(1, QCoreApplication.translate("BidBETONA", u"-2 ~ +2% (\uc870\ub2ec\uccad,\uacf5\uae30\uc5c5)", None))

        self.label_10.setText(QCoreApplication.translate("BidBETONA", u"\uc608\uac00\uc0b0\ucd9c", None))
        self.label_15.setText(QCoreApplication.translate("BidBETONA", u"1", None))
        self.label_16.setText(QCoreApplication.translate("BidBETONA", u"2", None))
        self.label_17.setText(QCoreApplication.translate("BidBETONA", u"3", None))
        self.label_18.setText(QCoreApplication.translate("BidBETONA", u"4", None))
        self.label_22.setText(QCoreApplication.translate("BidBETONA", u"5", None))
        self.label_23.setText(QCoreApplication.translate("BidBETONA", u"6", None))
        self.label_24.setText(QCoreApplication.translate("BidBETONA", u"7", None))
        self.label_25.setText(QCoreApplication.translate("BidBETONA", u"8", None))
        self.label_26.setText(QCoreApplication.translate("BidBETONA", u"9", None))
        self.label_27.setText(QCoreApplication.translate("BidBETONA", u"10", None))
        self.label_28.setText(QCoreApplication.translate("BidBETONA", u"11", None))
        self.label_29.setText(QCoreApplication.translate("BidBETONA", u"12", None))
        self.label_30.setText(QCoreApplication.translate("BidBETONA", u"13", None))
        self.label_31.setText(QCoreApplication.translate("BidBETONA", u"14", None))
        self.label_32.setText(QCoreApplication.translate("BidBETONA", u"15", None))
        self.txtDate.setText(QCoreApplication.translate("BidBETONA", u"\ub0a0\uc9dc", None))
        self.txtTime.setText(QCoreApplication.translate("BidBETONA", u"\uc2dc\uac04", None))
        self.label.setText("")
        self.btnReset.setText(QCoreApplication.translate("BidBETONA", u"\ucd08\uae30\ud654", None))
        self.btnSearch.setText(QCoreApplication.translate("BidBETONA", u"\uac80  \uc0c9 ", None))
        self.label_33.setText(QCoreApplication.translate("BidBETONA", u"\uc870\ub2ec\uacf5\uace0\ubc88\ud638\ub85c\uac80\uc0c9", None))
        self.label_34.setText(QCoreApplication.translate("BidBETONA", u"\ucc38\uac00\uc9c0\uc5ed", None))
        self.label_35.setText(QCoreApplication.translate("BidBETONA", u"\uc785\ucc30\ub9c8\uac10", None))
        self.comboBox6.setItemText(0, QCoreApplication.translate("BidBETONA", u"-3 ~ +3% (\uc548\uc804\ud589\uc815\ubd80)", None))
        self.comboBox6.setItemText(1, QCoreApplication.translate("BidBETONA", u"-2 ~ +2% (\uc870\ub2ec\uccad,\uacf5\uae30\uc5c5)", None))

        self.label_36.setText(QCoreApplication.translate("BidBETONA", u"\uacf5 \uace0  \uba85", None))
        self.label_37.setText(QCoreApplication.translate("BidBETONA", u"\uacf5\uace0\uae30\uad00", None))
        self.label_38.setText(QCoreApplication.translate("BidBETONA", u"\ub099  \ucc30  \uc728", None))
        self.label_39.setText(QCoreApplication.translate("BidBETONA", u"\uc785\ucc30\uc2dc\uc791", None))
        self.label_40.setText(QCoreApplication.translate("BidBETONA", u"\uacc4\uc57d\ubc29\ubc95", None))
        self.label_41.setText(QCoreApplication.translate("BidBETONA", u"\uacf5\uace0\ubc88\ud638", None))
        self.label_42.setText(QCoreApplication.translate("BidBETONA", u"\uac1c\ucc30\uc77c\uc2dc", None))
        self.label_43.setText(QCoreApplication.translate("BidBETONA", u"\uc608\uac00\ubc94\uc704", None))
        self.label_44.setText(QCoreApplication.translate("BidBETONA", u"\uae30\ucd08\uae08\uc561", None))
    # retranslateUi

