# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'bid.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

import bid_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1200, 745)
        MainWindow.setStyleSheet(u"background-color: rgb(255, 255, 255)")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(1060, 20, 121, 41))
        self.label.setPixmap(QPixmap(u"betonalogo.png"))
        self.label.setScaledContents(True)
        self.bidTitle = QLabel(self.centralwidget)
        self.bidTitle.setObjectName(u"bidTitle")
        self.bidTitle.setGeometry(QRect(0, 10, 451, 61))
        self.bidTitle.setPixmap(QPixmap(u"bidtitle.png"))
        self.bidResult1 = QFrame(self.centralwidget)
        self.bidResult1.setObjectName(u"bidResult1")
        self.bidResult1.setGeometry(QRect(20, 120, 311, 481))
        font = QFont()
        font.setFamily(u"\ub098\ub214\uace0\ub515")
        font.setPointSize(10)
        self.bidResult1.setFont(font)
        self.bidResult1.setAutoFillBackground(False)
        self.bidResult1.setStyleSheet(u"background-color: rgb(255, 255, 255)")
        self.bidResult1.setFrameShape(QFrame.StyledPanel)
        self.bidResult1.setFrameShadow(QFrame.Raised)
        self.label_3 = QLabel(self.bidResult1)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 20, 61, 21))
        self.txtResult1 = QLineEdit(self.bidResult1)
        self.txtResult1.setObjectName(u"txtResult1")
        self.txtResult1.setGeometry(QRect(90, 20, 191, 20))
        self.label_4 = QLabel(self.bidResult1)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 50, 61, 21))
        self.txtResult2 = QLineEdit(self.bidResult1)
        self.txtResult2.setObjectName(u"txtResult2")
        self.txtResult2.setGeometry(QRect(90, 50, 191, 20))
        self.label_5 = QLabel(self.bidResult1)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 80, 61, 21))
        self.txtResult3 = QLineEdit(self.bidResult1)
        self.txtResult3.setObjectName(u"txtResult3")
        self.txtResult3.setGeometry(QRect(90, 80, 191, 20))
        self.label_6 = QLabel(self.bidResult1)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 110, 61, 21))
        self.txtResult4 = QLineEdit(self.bidResult1)
        self.txtResult4.setObjectName(u"txtResult4")
        self.txtResult4.setGeometry(QRect(90, 110, 191, 20))
        self.txtResult5 = QLineEdit(self.bidResult1)
        self.txtResult5.setObjectName(u"txtResult5")
        self.txtResult5.setGeometry(QRect(90, 140, 191, 20))
        self.label_7 = QLabel(self.bidResult1)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 140, 61, 21))
        self.label_8 = QLabel(self.bidResult1)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 170, 61, 21))
        self.label_9 = QLabel(self.bidResult1)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 200, 61, 21))
        self.txtResult7 = QLineEdit(self.bidResult1)
        self.txtResult7.setObjectName(u"txtResult7")
        self.txtResult7.setGeometry(QRect(90, 200, 191, 20))
        self.txtResult9 = QLineEdit(self.bidResult1)
        self.txtResult9.setObjectName(u"txtResult9")
        self.txtResult9.setGeometry(QRect(90, 230, 191, 20))
        self.label_11 = QLabel(self.bidResult1)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 230, 61, 21))
        self.txtResult10 = QLineEdit(self.bidResult1)
        self.txtResult10.setObjectName(u"txtResult10")
        self.txtResult10.setGeometry(QRect(90, 260, 191, 20))
        self.label_12 = QLabel(self.bidResult1)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(20, 260, 61, 21))
        self.label_13 = QLabel(self.bidResult1)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(20, 290, 61, 21))
        self.txtResult11 = QLineEdit(self.bidResult1)
        self.txtResult11.setObjectName(u"txtResult11")
        self.txtResult11.setGeometry(QRect(90, 290, 191, 20))
        self.txtResult12 = QLineEdit(self.bidResult1)
        self.txtResult12.setObjectName(u"txtResult12")
        self.txtResult12.setGeometry(QRect(90, 320, 191, 20))
        self.label_14 = QLabel(self.bidResult1)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(20, 320, 61, 21))
        self.comboBox = QComboBox(self.bidResult1)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(90, 170, 191, 22))
        self.bidSearchFrame = QFrame(self.centralwidget)
        self.bidSearchFrame.setObjectName(u"bidSearchFrame")
        self.bidSearchFrame.setGeometry(QRect(470, 40, 511, 41))
        self.bidSearchFrame.setFont(font)
        self.bidSearchFrame.setAutoFillBackground(False)
        self.bidSearchFrame.setFrameShape(QFrame.StyledPanel)
        self.bidSearchFrame.setFrameShadow(QFrame.Raised)
        self.btnSearch = QPushButton(self.bidSearchFrame)
        self.btnSearch.setObjectName(u"btnSearch")
        self.btnSearch.setGeometry(QRect(410, 10, 75, 23))
        self.label_2 = QLabel(self.bidSearchFrame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 10, 121, 21))
        self.lineEdit = QLineEdit(self.bidSearchFrame)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(140, 9, 251, 21))
        self.btnAdd = QPushButton(self.centralwidget)
        self.btnAdd.setObjectName(u"btnAdd")
        self.btnAdd.setGeometry(QRect(340, 260, 31, 71))
        self.bidResult1_2 = QFrame(self.centralwidget)
        self.bidResult1_2.setObjectName(u"bidResult1_2")
        self.bidResult1_2.setGeometry(QRect(380, 120, 311, 481))
        self.bidResult1_2.setFont(font)
        self.bidResult1_2.setAutoFillBackground(False)
        self.bidResult1_2.setStyleSheet(u"background-color: rgb(255, 255, 255)")
        self.bidResult1_2.setFrameShape(QFrame.StyledPanel)
        self.bidResult1_2.setFrameShadow(QFrame.Raised)
        self.txtResult5_2 = QLineEdit(self.bidResult1_2)
        self.txtResult5_2.setObjectName(u"txtResult5_2")
        self.txtResult5_2.setGeometry(QRect(90, 20, 191, 20))
        self.label_19 = QLabel(self.bidResult1_2)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(20, 20, 61, 21))
        self.label_20 = QLabel(self.bidResult1_2)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(20, 50, 61, 21))
        self.label_21 = QLabel(self.bidResult1_2)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(20, 80, 61, 21))
        self.txtResult7_2 = QLineEdit(self.bidResult1_2)
        self.txtResult7_2.setObjectName(u"txtResult7_2")
        self.txtResult7_2.setGeometry(QRect(90, 80, 191, 20))
        self.comboBox_2 = QComboBox(self.bidResult1_2)
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(90, 50, 191, 22))
        self.label_10 = QLabel(self.bidResult1_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(110, 110, 61, 16))
        self.txtResult9_2 = QLineEdit(self.bidResult1_2)
        self.txtResult9_2.setObjectName(u"txtResult9_2")
        self.txtResult9_2.setGeometry(QRect(30, 140, 111, 20))
        self.label_15 = QLabel(self.bidResult1_2)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 140, 16, 21))
        self.txtResult9_3 = QLineEdit(self.bidResult1_2)
        self.txtResult9_3.setObjectName(u"txtResult9_3")
        self.txtResult9_3.setGeometry(QRect(30, 170, 111, 20))
        self.label_16 = QLabel(self.bidResult1_2)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(10, 170, 16, 21))
        self.txtResult9_4 = QLineEdit(self.bidResult1_2)
        self.txtResult9_4.setObjectName(u"txtResult9_4")
        self.txtResult9_4.setGeometry(QRect(30, 200, 111, 20))
        self.label_17 = QLabel(self.bidResult1_2)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(10, 200, 16, 21))
        self.txtResult9_5 = QLineEdit(self.bidResult1_2)
        self.txtResult9_5.setObjectName(u"txtResult9_5")
        self.txtResult9_5.setGeometry(QRect(30, 230, 111, 20))
        self.label_18 = QLabel(self.bidResult1_2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(10, 230, 16, 21))
        self.txtResult9_6 = QLineEdit(self.bidResult1_2)
        self.txtResult9_6.setObjectName(u"txtResult9_6")
        self.txtResult9_6.setGeometry(QRect(30, 260, 111, 20))
        self.label_22 = QLabel(self.bidResult1_2)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(10, 260, 16, 21))
        self.txtResult9_7 = QLineEdit(self.bidResult1_2)
        self.txtResult9_7.setObjectName(u"txtResult9_7")
        self.txtResult9_7.setGeometry(QRect(30, 290, 111, 20))
        self.label_23 = QLabel(self.bidResult1_2)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(10, 290, 16, 21))
        self.txtResult9_8 = QLineEdit(self.bidResult1_2)
        self.txtResult9_8.setObjectName(u"txtResult9_8")
        self.txtResult9_8.setGeometry(QRect(30, 320, 111, 20))
        self.label_24 = QLabel(self.bidResult1_2)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(10, 320, 16, 21))
        self.txtResult9_9 = QLineEdit(self.bidResult1_2)
        self.txtResult9_9.setObjectName(u"txtResult9_9")
        self.txtResult9_9.setGeometry(QRect(180, 140, 111, 20))
        self.label_25 = QLabel(self.bidResult1_2)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(160, 140, 16, 21))
        self.txtResult9_10 = QLineEdit(self.bidResult1_2)
        self.txtResult9_10.setObjectName(u"txtResult9_10")
        self.txtResult9_10.setGeometry(QRect(180, 170, 111, 20))
        self.label_26 = QLabel(self.bidResult1_2)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(160, 170, 16, 21))
        self.txtResult9_11 = QLineEdit(self.bidResult1_2)
        self.txtResult9_11.setObjectName(u"txtResult9_11")
        self.txtResult9_11.setGeometry(QRect(180, 200, 111, 20))
        self.label_27 = QLabel(self.bidResult1_2)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(160, 200, 16, 21))
        self.txtResult9_12 = QLineEdit(self.bidResult1_2)
        self.txtResult9_12.setObjectName(u"txtResult9_12")
        self.txtResult9_12.setGeometry(QRect(180, 230, 111, 20))
        self.label_28 = QLabel(self.bidResult1_2)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(160, 230, 16, 21))
        self.txtResult9_13 = QLineEdit(self.bidResult1_2)
        self.txtResult9_13.setObjectName(u"txtResult9_13")
        self.txtResult9_13.setGeometry(QRect(180, 260, 111, 20))
        self.label_29 = QLabel(self.bidResult1_2)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(160, 260, 16, 21))
        self.txtResult9_14 = QLineEdit(self.bidResult1_2)
        self.txtResult9_14.setObjectName(u"txtResult9_14")
        self.txtResult9_14.setGeometry(QRect(180, 290, 111, 20))
        self.label_30 = QLabel(self.bidResult1_2)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(160, 290, 16, 21))
        self.txtResult9_15 = QLineEdit(self.bidResult1_2)
        self.txtResult9_15.setObjectName(u"txtResult9_15")
        self.txtResult9_15.setGeometry(QRect(180, 320, 111, 20))
        self.label_31 = QLabel(self.bidResult1_2)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(160, 320, 16, 21))
        self.txtResult9_16 = QLineEdit(self.bidResult1_2)
        self.txtResult9_16.setObjectName(u"txtResult9_16")
        self.txtResult9_16.setGeometry(QRect(180, 350, 111, 20))
        self.label_32 = QLabel(self.bidResult1_2)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(160, 350, 16, 21))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText("")
        self.bidTitle.setText("")
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\uacf5\uace0\ubc88\ud638", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\uacf5 \uace0  \uba85", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"\uacf5\uace0\uae30\uad00", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\uacc4\uc57d\ubc29\ubc95", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\uae30\ucd08\uae08\uc561", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"\uc608\uac00\ubc94\uc704", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"\ub099  \ucc30  \uc728", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"\ucc38\uac00\uc9c0\uc5ed", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"\uac1c\ucc30\uc77c\uc2dc", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"\uc785\ucc30\uc2dc\uc791", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"\uc785\ucc30\ub9c8\uac10", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"-3 ~ +3% (\uc548\uc804\ud589\uc815\ubd80)", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"-2 ~ +2% (\uc870\ub2ec\uccad,\uacf5\uae30\uc5c5)", None))

        self.btnSearch.setText(QCoreApplication.translate("MainWindow", u"\uac80  \uc0c9 ", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\uc870\ub2ec\uacf5\uace0\ubc88\ud638\ub85c\uac80\uc0c9", None))
        self.btnAdd.setText(QCoreApplication.translate("MainWindow", u">>", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"\uae30\ucd08\uae08\uc561", None))
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"\uc608\uac00\ubc94\uc704", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"\ub099  \ucc30  \uc728", None))
        self.comboBox_2.setItemText(0, QCoreApplication.translate("MainWindow", u"-3 ~ +3% (\uc548\uc804\ud589\uc815\ubd80)", None))
        self.comboBox_2.setItemText(1, QCoreApplication.translate("MainWindow", u"-2 ~ +2% (\uc870\ub2ec\uccad,\uacf5\uae30\uc5c5)", None))

        self.label_10.setText(QCoreApplication.translate("MainWindow", u"\uc608\uac00\uc0b0\ucd9c", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"7", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"8", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"9", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"10", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"11", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"12", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"13", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"14", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"15", None))
    # retranslateUi

